-- Kamsar o Bar - initial schema.
-- Written in portable SQL so it runs on PostgreSQL (production) and H2 (local dev / tests).

CREATE TABLE cities (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(100) NOT NULL,
    state               VARCHAR(100),
    whatsapp_group_url  VARCHAR(500),
    bank_account_name   VARCHAR(150),
    bank_account_number VARCHAR(50),
    bank_ifsc           VARCHAR(20),
    bank_name           VARCHAR(150),
    upi_id              VARCHAR(100),
    active              BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_cities_name UNIQUE (name)
);

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(120) NOT NULL,
    mobile          VARCHAR(20)  NOT NULL,
    password_hash   VARCHAR(100) NOT NULL,
    role            VARCHAR(20)  NOT NULL,
    city_id         BIGINT       NOT NULL REFERENCES cities (id),
    managed_city_id BIGINT REFERENCES cities (id),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_mobile UNIQUE (mobile)
);
CREATE INDEX idx_users_city ON users (city_id);
CREATE INDEX idx_users_role ON users (role);

-- Normalised lookup tables let many members point to the same company / skill,
-- give us autocomplete for free and keep the search on an indexed column.
CREATE TABLE companies (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(150) NOT NULL,
    normalized_name VARCHAR(150) NOT NULL,
    CONSTRAINT uk_companies_normalized UNIQUE (normalized_name)
);

CREATE TABLE skills (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    normalized_name VARCHAR(100) NOT NULL,
    CONSTRAINT uk_skills_normalized UNIQUE (normalized_name)
);

CREATE TABLE user_profiles (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    linkedin_url        VARCHAR(300),
    current_company     VARCHAR(150),
    position            VARCHAR(150),
    years_of_experience INT,
    bio                 VARCHAR(1000),
    open_to_help        BOOLEAN      NOT NULL DEFAULT TRUE,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_profiles_user UNIQUE (user_id)
);

CREATE TABLE profile_referral_companies (
    profile_id BIGINT NOT NULL REFERENCES user_profiles (id) ON DELETE CASCADE,
    company_id BIGINT NOT NULL REFERENCES companies (id),
    PRIMARY KEY (profile_id, company_id)
);
CREATE INDEX idx_prc_company ON profile_referral_companies (company_id);

CREATE TABLE profile_skills (
    profile_id BIGINT NOT NULL REFERENCES user_profiles (id) ON DELETE CASCADE,
    skill_id   BIGINT NOT NULL REFERENCES skills (id),
    PRIMARY KEY (profile_id, skill_id)
);
CREATE INDEX idx_ps_skill ON profile_skills (skill_id);

CREATE TABLE posts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id  BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    city_id    BIGINT        NOT NULL REFERENCES cities (id),
    category   VARCHAR(30)   NOT NULL,
    title      VARCHAR(200)  NOT NULL,
    content    VARCHAR(5000) NOT NULL,
    created_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_posts_city_created ON posts (city_id, created_at);

CREATE TABLE comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    BIGINT        NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    author_id  BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    content    VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_comments_post ON comments (post_id, created_at);

CREATE TABLE campaigns (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id       BIGINT        NOT NULL REFERENCES cities (id),
    title         VARCHAR(200)  NOT NULL,
    description   VARCHAR(3000),
    goal_amount   DECIMAL(12, 2),
    active        BOOLEAN       NOT NULL DEFAULT TRUE,
    created_by_id BIGINT REFERENCES users (id) ON DELETE SET NULL,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_campaigns_city ON campaigns (city_id);

CREATE TABLE donations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id         BIGINT         NOT NULL REFERENCES cities (id),
    campaign_id     BIGINT REFERENCES campaigns (id) ON DELETE SET NULL,
    donor_id        BIGINT REFERENCES users (id) ON DELETE SET NULL,
    donor_name      VARCHAR(120)   NOT NULL,
    amount          DECIMAL(12, 2) NOT NULL,
    transaction_ref VARCHAR(100),
    note            VARCHAR(500),
    anonymous       BOOLEAN        NOT NULL DEFAULT FALSE,
    status          VARCHAR(20)    NOT NULL,
    verified_by_id  BIGINT REFERENCES users (id) ON DELETE SET NULL,
    created_at      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verified_at     TIMESTAMP
);
CREATE INDEX idx_donations_city_status ON donations (city_id, status);
CREATE INDEX idx_donations_campaign ON donations (campaign_id);
