-- Mobile push notifications.
CREATE TABLE device_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token        VARCHAR(255) NOT NULL,
    platform     VARCHAR(20),
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_device_tokens_token UNIQUE (token)
);
CREATE INDEX idx_device_tokens_user ON device_tokens (user_id);

-- Each member chooses what they are notified about.
ALTER TABLE users ADD COLUMN notify_city_posts BOOLEAN DEFAULT TRUE NOT NULL;
ALTER TABLE users ADD COLUMN notify_city_events BOOLEAN DEFAULT TRUE NOT NULL;
ALTER TABLE users ADD COLUMN notify_all_events BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE users ADD COLUMN notify_event_reminders BOOLEAN DEFAULT TRUE NOT NULL;

-- So each "starting soon" reminder is sent once, even with several backend instances.
ALTER TABLE event_attendees ADD COLUMN reminder_sent_at TIMESTAMP;
