package com.kamsarobar.media;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;

import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Component;

import com.kamsarobar.config.AppProperties;

@Component
public class FileSystemImageStorage implements ImageStorage {

    private final Path root;

    public FileSystemImageStorage(AppProperties properties) {
        this.root = Path.of(properties.storage().localPath()).toAbsolutePath().normalize();
        try {
            Files.createDirectories(root);
        } catch (IOException ex) {
            throw new UncheckedIOException("Cannot create upload directory " + root, ex);
        }
    }

    @Override
    public void save(String key, byte[] content) {
        Path target = resolve(key);
        try {
            Files.createDirectories(target.getParent());
            Files.write(target, content);
        } catch (IOException ex) {
            throw new UncheckedIOException("Could not store image", ex);
        }
    }

    @Override
    public Resource load(String key) {
        Path file = resolve(key);
        return Files.isRegularFile(file) ? new FileSystemResource(file) : null;
    }

    @Override
    public void delete(String key) {
        try {
            Files.deleteIfExists(resolve(key));
        } catch (IOException ex) {
            throw new UncheckedIOException("Could not delete image", ex);
        }
    }

    /** Keys are generated by the server, but guard against path traversal anyway. */
    private Path resolve(String key) {
        Path path = root.resolve(key).normalize();
        if (!path.startsWith(root)) {
            throw new IllegalArgumentException("Invalid storage key");
        }
        return path;
    }
}
